"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.plugin = exports.details = void 0;
/* eslint no-plusplus: ["error", { "allowForLoopAfterthoughts": true }] */
var details = function () { return ({
	id: 'mitsie_detect_crop',
	name: 'Detect Crop',
	description: 'Detect the Crop values of a video, can then use "args.variables.cropCommand" as a video filter to crop the video \n\n \n\n or command compiled using "args.variables.cropHeight", "args.variables.cropwidth", "args.variables.cropX", "args.variables.cropY"\n\n',
	style: {
        borderColor: 'orange',
	},
	tags: 'Crop',
	isStartPlugin: false,
	pType: '',
	requiresVersion: '2.40.01',
	sidebarPosition: 1,
	icon: 'faQuestion',
	inputs: [
		{
			label: 'Frames To Check',
			name: 'FramesToCheck',
			type: 'number', 
			defaultValue: '', 
			inputUI: {
				type: 'text', 
			},
			tooltip: 'Number of frames to Check against e.g. 50.', 
		},
		{
			label: 'No of Snippets To Check',
			name: 'SnippetsToCheck',
			type: 'number', 
			defaultValue: '', 
			inputUI: {
				type: 'text', 
			},
			tooltip: 'Number of snippets of the video to check against e.g. 4.', 
		},
		{
			label: 'Minimum Crop in Px',
			name: 'MinimumCrop',
			type: 'number',
			defaultValue: '',
			inputUI: {
				type: 'text',
			},
			tooltip: 'Minimum size reduction in pixels before crop is detected e.g. 10',
		},
		{
			label: 'Direction of Crop',
			name: 'CropDirection',
			type: 'string',         
			defaultValue: 'Both',  
			inputUI: {
				type: 'dropdown',
				options: [
					'Both',
					'Width',
					'Height',
				],
			},
			tooltip: `Choose which direction to detect crop, Width or Height or Both Directions`,
		},
		{
			label: 'Generate Thumbnails',
			name: 'GenerateThumbnails',
			type: 'string',         
			defaultValue: 'Yes',  
			inputUI: {
				type: 'dropdown',
				options: [
					'Yes',
					'No',
				],
			},
			tooltip: `Generate before and after thumbnails for the crop, stored in the original file directory`,
		},
		{
			label: 'Keep Crop Report File',
			name: 'KeepCropFile',
			type: 'string',         
			defaultValue: 'No',  
			inputUI: {
				type: 'dropdown',
				options: [
					'No',
					'Yes',
				],
			},
			tooltip: `Keep the crop report generated by FFMPEG alongslide the video file?`,
		},
	],
    outputs: [
        {
            number: 1,
            tooltip: 'Detected Crop',
        },
		{
            number: 2,
            tooltip: 'No Crop',
        },
    ],
}); };
exports.details = details;

var plugin = function (args) {
	
    var lib = require('../../../../../methods/lib')(); 
	const fs = require("fs");
	const execSync = require("child_process").execSync;
	
    // eslint-disable-next-line @typescript-eslint/no-unused-vars,no-param-reassign
	var inputs = lib.loadDefaultValues(args.inputs, details);
	var file = args.originalLibraryFile;
	
	var source = file.meta.SourceFile; //source file
	var dir = file.meta.Directory; //source directory
	
	var sourcename = file.meta.FileName.substring(
		0,
		file.meta.FileName.lastIndexOf(".")
	); //filename without extension
	
	function generate_crop_values(file, inputs, args) {
		
		var cropfile = `${dir}/${sourcename}.crop`; //location and name of the crop file
		
		var returns = {
			crop_height: 0, //return value for this function
			crop_width: 0, //return value for this function
			crop_x: 0, //return value for this function
			crop_y: 0, //return value for this function
			log: ``,
		};

		//parse cropdetect output in Node.js instead of awk/tail (cross-platform)
		const parseCropdetect = function(cmd, line_count=250) {
			line_count = -Math.abs(line_count);
			const output = execSync(cmd, { encoding: 'utf-8' });
			const lines = output.split('\n')
				.filter(function(line) { return line.includes('crop='); })
				.map(function(line) {
					const match = line.match(/crop=\S+/);
					return match ? match[0] : null;
				})
				.filter(Boolean);
			return lines.slice(line_count).join('\n');
		};
	  
		const createCropObj  = function(seconds, cframes){
		  
			var cropObj = {
				seconds: 0,
				cframes: 0,
			};
			
			cropObj.seconds = seconds;
			cropObj.cframes = cframes;
			
			return cropObj;
		}
	  
		const calculateCropPoints = function(vid_length, frames_to_check=400, total_frames, split_count = 4){
		
			var cropPoint = [];
			
			if(vid_length > 1 && vid_length != null && frames_to_check != "" && frames_to_check != null && parseInt(frames_to_check) > 1){
				
				if(parseInt(frames_to_check) > total_frames){
					frames_to_check = total_frames;
				}
				
				var frame_count = Math.abs(Math.ceil(parseInt(frames_to_check) / split_count));
				var part_length = 0;
				// add the very start of the video
				cropPoint.push( createCropObj(1, frame_count) );
				
				part_length = Math.abs(Math.ceil(vid_length / split_count));
				for (var i = 1; i < split_count; i++) {
					cropPoint.push( createCropObj( Math.ceil(part_length * i) , frame_count) );
				}
			}
			
			return cropPoint;
		
		}

		//create crop value
		if (!fs.existsSync(`${cropfile}`)) {
			
			returns.log += `Creating crop values...\n`;
			var vid_length = Math.abs(parseInt( file.duration ));
			var frame_rate = Math.abs(parseInt( file.meta.VideoFrameRate ));
			var total_frames = vid_length * frame_rate;
		
			returns.log += `--- Video Length: ${vid_length}\n`;
			returns.log += `--- Frame Count: ${total_frames}\n`;
			
			// generate the crop points
			var cropPoints = calculateCropPoints(vid_length, inputs.FramesToCheck, total_frames, inputs.SnippetsToCheck);
			
			let cropData = ``;
			for (var i = 0; i < cropPoints.length; i++) {
				returns.log += `--- Checking: ${cropPoints[i].cframes} Frames at : ${cropPoints[i].seconds} Seconds into Video \n`;
				cropData += parseCropdetect(
				  `"${args.ffmpegPath}" -ss ${cropPoints[i].seconds} -i "${source}" -frames:v ${cropPoints[i].cframes} -vf cropdetect -f null - 2>&1`, cropPoints[i].cframes
				);
				cropData += `\n`; // add an additional new line
			}
			if(cropData != ""){
				fs.writeFileSync(cropfile, cropData);
			}
		
		} else {
			returns.log += `Crop values already exist, Using Existing File \n`;
		}

		//get data from cropvalue.crop text file
		var data = fs.readFileSync(`${cropfile}`).toString().split("\n"); //full data from cropvalue txt file

		//get details of the to be cropped video
		returns.log += `--------- DATA ---------\n`;
		var crop;
		var previous_crop_height = 0;
		var previous_crop_width = 0;
		var current_snippet = 1;
		var snippet_frames = parseInt(inputs.FramesToCheck) / parseInt(inputs.SnippetsToCheck);
		for (var c = 0; c < data.length; c++) {
		
			returns.log += data[c];
			returns.log += `\n`;
			if(c == current_snippet * snippet_frames){
				returns.log += `--------- Check Point ---------\n`;
				current_snippet = current_snippet+1;
			}
		
			if(data.hasOwnProperty(c)){
				crop = data[c].split("=");
				if(crop.hasOwnProperty(1)){
					crop = crop[1].split(":");
					if(crop.hasOwnProperty(0) && crop.hasOwnProperty(1) && crop.hasOwnProperty(2) && crop.hasOwnProperty(3)){
						var crop_width = parseInt(crop[0]);
						var crop_height = parseInt(crop[1]);
						var crop_x = parseInt(crop[2]);
						var crop_y = parseInt(crop[3]);
						
						if(crop_height > 0 && crop_width > 0){
							if(crop_height != previous_crop_height || crop_width != previous_crop_width){
								if (crop_height > returns.crop_height || crop_width > returns.crop_width) {
								  
									returns.crop_height = crop_height;							  
									returns.crop_width = crop_width;
									returns.crop_x = crop_x;							  
									returns.crop_y = crop_y;
								  
									returns.log += `New crop height: ${crop_height}\n`;
									returns.log += `New crop width: ${crop_width}\n`;
									returns.log += `New crop x: ${crop_x}\n`;
									returns.log += `New crop y: ${crop_y}\n`;
								  
								}
								previous_crop_height = crop_height;
								previous_crop_width = crop_width;
							}
						}
					}
				}
			}
		
		}
		returns.log += `\n--------- END DATA ---------\n`;
	  
		if(inputs.KeepCropFile == "No"){
			fs.unlinkSync(`${cropfile}`);
		}
	  
		return returns;
	}
	
	function generate_crop_thumbnails(file, inputs, args){
		
		var image_extension = "png";
		var before_crop_img = `${dir}/${sourcename}_thumb_1_b4Crop.${image_extension}`; //location and name of the before image
		args.variables.beforeCropImg = `${sourcename}_thumb_1_b4Crop.${image_extension}`;
		var after_crop_img = `${dir}/${sourcename}_thumb_2_afCrop.${image_extension}`; //location and name of the after image
		args.variables.afterCropImg = `${sourcename}_thumb_2_afCrop.${image_extension}`;
			
		var vid_length = Math.abs(parseInt( file.duration ));
		var snapshot_time = vid_length / 2;
		
		//generate image in Node.js instead of awk/tail (cross-platform)
		const generateCropIMG = function(cmd) {
			const output = execSync(cmd, { encoding: 'utf-8' });			
			return output;
		};
		
		// generate the crop images
		if (!fs.existsSync(`${before_crop_img}`)) {
			generateCropIMG(`"${args.ffmpegPath}" -ss ${snapshot_time} -i "${source}" -frames:v 1 -vf "blackframe=0,metadata=select:key=lavfi.blackframe.pblack:value=50:function=less" -update true -q:v 2 -f image2 "${before_crop_img}"`);			
		}
		if (!fs.existsSync(`${after_crop_img}`)) {
			generateCropIMG(`"${args.ffmpegPath}" -ss ${snapshot_time} -i "${source}" -frames:v 1 -vf "blackframe=0,metadata=select:key=lavfi.blackframe.pblack:value=50:function=less,${args.variables.cropCommand}" -update true -q:v 2 -f image2 "${after_crop_img}"`);
		}
	}
	
	var cropVals = generate_crop_values(file, inputs, args);
	
	args.jobLog( cropVals.log );
	
	var minimumDifference = parseInt(inputs.MinimumCrop);
	var videoHeight = parseInt(file.meta.ImageHeight);
	var videoWidth = parseInt(file.meta.ImageWidth);
	var minimumHeight = videoHeight - minimumDifference;
	var minimumWidth = videoWidth - minimumDifference;
	
	var same_resolution = true;
	var below_minimum = false;
	
	// check the size and decide if it needs cropping
	if(cropVals.crop_height != 0 && cropVals.crop_width != 0){
		same_resolution = false;
		if(inputs.CropDirection == "Both"){
			if(cropVals.crop_height <= minimumHeight || cropVals.crop_width <= minimumWidth){
				below_minimum = true;
			}
		}else if(inputs.CropDirection == "Width"){
			if(cropVals.crop_width <= minimumWidth){
				below_minimum = true;
			}
		}else if(inputs.CropDirection == "Height"){
			if(cropVals.crop_height <= minimumHeight){
				below_minimum = true;
			}
		}
	}
	
	if( same_resolution == false && below_minimum == true ){
	
		args.variables.cropHeight = cropVals.crop_height;
		args.variables.cropWidth = cropVals.crop_width;
		args.variables.cropX = cropVals.crop_x;
		args.variables.cropY = cropVals.crop_y;
		args.variables.cropCommand = `crop=${cropVals.crop_width}:${cropVals.crop_height}:${cropVals.crop_x}:${cropVals.crop_y}`;
		// add to the job log
		args.jobLog( args.variables.cropCommand );
		
		// generate thumbnails if needed
		if(inputs.GenerateThumbnails == "Yes"){
			var thumb_output = generate_crop_thumbnails(file, inputs, args);
		}
	
		// crop true
		args.jobLog(`CROP VIDEO Required: `);
		args.jobLog(`   Video Height: ${videoHeight}`);
		args.jobLog(`   Video Width: ${videoWidth}`);
		args.jobLog(`   Minimum Height: ${minimumHeight}`);
		args.jobLog(`   Minimum Width: ${minimumWidth}`);
		args.jobLog(`VALUES: `);
		args.jobLog(`   Crop Height: ${args.variables.cropHeight} Crop Width: ${args.variables.cropWidth} Crop X: ${args.variables.cropX} Crop Y: ${args.variables.cropY} `);
		return {
			outputFileObj: args.inputFileObj,
			outputNumber: 1,
			variables: args.variables,
		};
	}else{
		// crop false
		args.jobLog(`NO CROP Required: `);
		args.jobLog(`   Video Height: ${videoHeight}`);
		args.jobLog(`   Video Width: ${videoWidth}`);
		args.jobLog(`   Minimum Height: ${minimumHeight}`);
		args.jobLog(`   Minimum Width: ${minimumWidth}`);
		return {
			outputFileObj: args.inputFileObj,
			outputNumber: 2,
			variables: args.variables,
		};
	}
	
};
exports.plugin = plugin;
